//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSMonsterReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSMonsterReference.WSConversorUnidades")]
    public interface WSConversorUnidades
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversorUnidades/login", ReplyAction="http://tempuri.org/WSConversorUnidades/loginResponse")]
        System.Threading.Tasks.Task<string> loginAsync(string usuario, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversorUnidades/convertirLongitud", ReplyAction="http://tempuri.org/WSConversorUnidades/convertirLongitudResponse")]
        System.Threading.Tasks.Task<double> convertirLongitudAsync(double valor, string unidadInicial, string unidadFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversorUnidades/convertirMasa", ReplyAction="http://tempuri.org/WSConversorUnidades/convertirMasaResponse")]
        System.Threading.Tasks.Task<double> convertirMasaAsync(double valor, string unidadInicial, string unidadFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversorUnidades/convertirTemperatura", ReplyAction="http://tempuri.org/WSConversorUnidades/convertirTemperaturaResponse")]
        System.Threading.Tasks.Task<double> convertirTemperaturaAsync(double valor, string unidadInicial, string unidadFinal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface WSConversorUnidadesChannel : WSMonsterReference.WSConversorUnidades, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class WSConversorUnidadesClient : System.ServiceModel.ClientBase<WSMonsterReference.WSConversorUnidades>, WSMonsterReference.WSConversorUnidades
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSConversorUnidadesClient() : 
                base(WSConversorUnidadesClient.GetDefaultBinding(), WSConversorUnidadesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_WSConversorUnidades.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSConversorUnidadesClient(EndpointConfiguration endpointConfiguration) : 
                base(WSConversorUnidadesClient.GetBindingForEndpoint(endpointConfiguration), WSConversorUnidadesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSConversorUnidadesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSConversorUnidadesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSConversorUnidadesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSConversorUnidadesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSConversorUnidadesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> loginAsync(string usuario, string contrasenia)
        {
            return base.Channel.loginAsync(usuario, contrasenia);
        }
        
        public System.Threading.Tasks.Task<double> convertirLongitudAsync(double valor, string unidadInicial, string unidadFinal)
        {
            return base.Channel.convertirLongitudAsync(valor, unidadInicial, unidadFinal);
        }
        
        public System.Threading.Tasks.Task<double> convertirMasaAsync(double valor, string unidadInicial, string unidadFinal)
        {
            return base.Channel.convertirMasaAsync(valor, unidadInicial, unidadFinal);
        }
        
        public System.Threading.Tasks.Task<double> convertirTemperaturaAsync(double valor, string unidadInicial, string unidadFinal)
        {
            return base.Channel.convertirTemperaturaAsync(valor, unidadInicial, unidadFinal);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_WSConversorUnidades))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_WSConversorUnidades))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50774/WSConversorUnidades.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WSConversorUnidadesClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_WSConversorUnidades);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WSConversorUnidadesClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_WSConversorUnidades);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_WSConversorUnidades,
        }
    }
}
